# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]

# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
ADMIN_NAME: 'First User'
ADMIN_EMAIL: 'user@example.com'
ADMIN_PASSWORD: 'changeme'
DOMAIN_NAME: 'cvdtc.lvh.me'
SECRET_KEY_BASE: ''
PROGRESS_BAR_TIMEOUT: '10000'
IEV_VERSION: '1.0'
IEV_HOST: 'http://localhost'
IEV_PORT: '8080'
IEV_PATH: 'cvdtc_cv'
IEV_REFERENTIAL: 'anonymous'
BITLY_TOKEN: '' # used to shorten URL
NUMBER_RESULTS_PER_PAGE: '100'
SMTP_DELIVERY_METHOD: 'SMTP'
SMTP_HOST: 'localhost'
SMTP_PORT: '1025'
SMTP_DOMAIN:
SMTP_USER_NAME:
SMTP_PASSWORD:
SMTP_AUTHENTICATION:
NEWRELIC: ''
CHECK_GTE3: ''
SPEC_VALIDATION_URL: 'http://www.chouette.mobi/validation/V2_3'
